# Generated by Django 5.2.7 on 2025-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.CharField(default='📄', max_length=10, verbose_name='アイコン'),
        ),
    ]
