# Generated by Django 5.2.7 on 2025-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'ページ', 'verbose_name_plural': 'ページ'},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
    ]
